---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: create a user
      user:
         name: Joyy
         shell: /sbin/nologin
      tags:
        - copyuser

    - name: Install httpd package
      yum:
         name: httpd
         state: latest
      tags:
        - install

    - name: Start a service
      service:
         name: httpd
         state: started
