---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    default_pass: defaultpassword
  tasks:
    - lineinfile:
        path: /var/www/html/index.html
        regexp: '^<br>application_password='
        line: '<br>application_password= {{ default_pass }}'
      notify:
        - start httpd
        - print the username

  handlers:
    - name: start httpd
      service: name=httpd state=started

    - name: print the username
      debug: msg="Logged in as user centos"
